search:
  authorization:
    kakao-auth: KakaoAK cfb766ea794157a822528c71cd38ce0b
    naver-client-id: UmSwQxTOfWrSkmxm9fUt
    naver-client-secret: f6kNJnt1ft
  blog:
    kakao-url: https://dapi.kakao.com
    kakao-path: /v2/search/blog
    naver-url: https://openapi.naver.com
    naver-path: /v1/search/blog.json

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:search
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true